// <auto-generated />
using System;
using ForecastAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForecastAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210916090324_Seed users")]
    partial class Seedusers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForecastAPI.Data.Entities.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.RegisterConfirm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RegisterConfirms");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Email = "admin@brainence.com",
                            Name = "Admin",
                            Password = "$2a$11$ghVeDxJnFkYs8bTTgM4WdeEZ76NkRdIHNp/QY2o8hy8Rcvx/EjwKm",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Email = "admin2@brainence.com",
                            Name = "Admin2",
                            Password = "$2a$11$E5gjPw6XuNnob1511witn.u4/sG75QgqGmA8/n2pibNIcyqsnBJki",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Email = "mark@brainence.com",
                            Name = "Mark",
                            Password = "$2a$11$STG3hRKruvyP.3SqcUrhSOjGIzg.HlJdBMZger308IGhwG3q252T6",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Email = "iryna@brainence.com",
                            Name = "Iryna",
                            Password = "$2a$11$BKItgl0UcRQLQmZsorJaC.SaPnYY3jtN86u7Mhm/74aynZa8lHtp6",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.VerifyPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VerifyPasswords");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.History", b =>
                {
                    b.HasOne("ForecastAPI.Data.Entities.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("ForecastAPI.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ForecastAPI.Data.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.RegisterConfirm", b =>
                {
                    b.HasOne("ForecastAPI.Data.Entities.User", "User")
                        .WithOne("RegisterConfirm")
                        .HasForeignKey("ForecastAPI.Data.Entities.RegisterConfirm", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.VerifyPassword", b =>
                {
                    b.HasOne("ForecastAPI.Data.Entities.User", "User")
                        .WithOne("VerifyPassword")
                        .HasForeignKey("ForecastAPI.Data.Entities.VerifyPassword", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForecastAPI.Data.Entities.User", b =>
                {
                    b.Navigation("History");

                    b.Navigation("RegisterConfirm");

                    b.Navigation("VerifyPassword");
                });
#pragma warning restore 612, 618
        }
    }
}
